name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Navigate to the project directory
            cd /var/www/arrowasphaltstriping.com

            # Pull latest changes from GitHub
            git fetch origin main
            git reset --hard origin/main

            # Ensure Ruby version
            rbenv local 3.1.4 || { echo "Ruby 3.1.4 not found. Please install."; exit 1; }

            # Install Jekyll and Bundler with the correct version
            gem install bundler jekyll

            # Clear Gemfile.lock to avoid stale or incompatible dependencies
            rm -f Gemfile.lock
            bundle config set --local path 'vendor/bundle'
            bundle install

            # Clear Jekyll cache for a fresh build
            rm -rf .jekyll-cache

            # Clean and fully rebuild the Jekyll site for production
            JEKYLL_ENV=production bundle exec jekyll build --trace

            # Restart Apache to apply the changes
            sudo systemctl restart apache2
