jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\n' | cut -c -100 # Print only first 100 chars for debug

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/arrowasphaltstriping.com
            git pull origin main
