- name: Deploy to VPS
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    port: 22
    script: |
      cd /var/www/arrowasphaltstriping.com
      git pull origin main
      JEKYLL_ENV=production bundle exec jekyll build
      sudo systemctl restart apache2
